name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install
      run: |
        npm ci
        npm run install:app
    - name: Build
      run: |
        npm run build:all
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          releases/linux.zip
          releases/mac.zip
          releases/win64.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
