name: Push dev

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Discord notification
      env:
        DISCORD_USERNAME: GitHub
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_HOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'New commit to dev by {{ EVENT_PAYLOAD.pusher.name }}'
